version: '3'

services:
  earth:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"

  satellite:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"

  rabbitmq:
    ports:
      - "15672:15672"
      - "5672:5672"